/**
 * @file gnuplot.cpp 
 * @author Christian Laguerre <christian.laguerre@math.cnrs.fr> (2012-2015)
 * @version 1.06.00
 * @date 2015-02-19
 *
 * @brief %Gnuplot output
 * @details 
 * %Output format:
 * optimized for %Gnuplot (for huz_evolution.dat).
 *
 * @copyright License Cecill-V2 \n
 * <http://www.cecill.info/licences/Licence_CeCILL_V2-en.html>
 *
 * (c) CNRS - Universite d'Orleans - BRGM (France)
 */
/* 
 *
 * This file is part of FullSWOF_2D software. 
 * <https://sourcesup.renater.fr/projects/fullswof-2d/> 
 *
 * FullSWOF_2D = Full Shallow-Water equations for Overland Flow, 
 * in two dimensions of space.
 * This software is a computer program whose purpose is to compute
 * solutions for 2D Shallow-Water equations.
 *
 * LICENSE
 *
 * This software is governed by the CeCILL license under French law and
 * abiding by the rules of distribution of free software. You can use,
 * modify and/ or redistribute the software under the terms of the CeCILL
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * <http://www.cecill.info>.
 *
 * As a counterpart to the access to the source code and rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty and the software's author, the holder of the
 * economic rights, and the successive licensors have only limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading, using, modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean that it is complicated to manipulate, and that also
 * therefore means that it is reserved for developers and experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and, more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 *
 ******************************************************************************/


#include "gnuplot.hpp"

Gnuplot::Gnuplot(Parameters & par):Output(par){
  
  /**
   * @details  
   * Writes the header of the file 'huz_evolution.dat'.
   * @param[in] par parameter, contains all the values from the parameters file.
   * @warning Impossible to open the *** file. Verify if the directory *** exists.
   * @note If huz_evolution.dat cannot be opened, the code will exit with failure termination code.
   */
   
  outputDirectory = par.get_outputDirectory();
  namefile = outputDirectory + "huz_evolution.dat";
  
  ofstream outsave(namefile.c_str(),ios::out);
  if (!outsave){
    cout << "Impossible to open the " << namefile.c_str() <<" file\n";
    cout << "Verify if the directory " << outputDirectory <<" exists\n";
    exit(EXIT_FAILURE);
  }
  outsave << "################################################################## "<< endl;
  outsave << "# Generated by "<< VERSION << endl; 
  outsave << "################################################################## "<< endl;
  
  outsave << "# (i-0.5)*dx " << "\t"<< setw(9) << "(j-0.5)*dy" << "\t"<< setw(9) << " h[i][j] " << "\t"<< setw(9) << " u[i][j] " << "\t"<< setw(9) << "v[i][j]" << "\t"<< setw(9) << " h[i][j]+z[i][j] "<< "\t"<< setw(9) << " z[i][j] " << "\t"<< setw(9) << " norm_U[i][j] " << "\t"<< setw(9) << "Fr[i][j] (Froude)" << "\t"<< setw(9) << "qx[i][j]" << "\t"<< setw(9) << "qy[i][j]" << "\t"<< setw(9) << "q[i][j]" << endl;
  outsave << "# " << endl;
  outsave.close();
  
}

void Gnuplot::write(TAB h,TAB u,TAB v,TAB z, SCALAR time){
  
  /**
   * @details
   * Writes the values of Scheme#h, Scheme#u (=q1/h), Scheme#v (=q2/h), Scheme#h+ Scheme#z (free surface),
   * Scheme#z, \f$ |U| = \sqrt{u^2+v^2}\f$, the Froude number \f$ \frac{|U|}{\sqrt{gh}}\f$, Scheme#q1, Scheme#q2,
   * and \f$ h|U|\f$ at the current time in huz_evolution.dat. \n
   * If the water height is too small, we replace it by 0, the velocity is null and the Froude number does not exist.
   * @param[in] h the water height.
   * @param[in] u first componant of the velocity.
   * @param[in] v second componant of the velocity.
   * @param[in] z the topography.
   * @param[in] time the current time.
   */
  
  ofstream outsave(namefile.c_str(),ios::app);  
  outsave << "# time : "<< time << " seconds "<<endl;
  for (int i=1;i<NXCELL+1;i++){
    for (int j=1 ; j<NYCELL+1 ; j++){
      if (h[i][j]<HE_CA){
        outsave << (i-0.5)*DX << "\t" << setw(9) << (j-0.5)*DY << "\t" << setw(9) << "0.0" << "\t" << setw(9) << "0.0" << "\t" << setw(9) << "0.0" << "\t" << setw(9) << z[i][j] << "\t" << setw(9) << z[i][j] << "\t" << setw(9) << "0.0" << "\t" << setw(9) << "NaN" << "\t" << setw(9) << "0.0" << "\t" << setw(9) << "0.0" << "\t" << setw(9) << "0.0" << endl;
      }
      else{
        outsave << (i-0.5)*DX << "\t" << setw(9) << (j-0.5)*DY << "\t" << setw(9) << h[i][j] << "\t" << setw(9) << u[i][j] << "\t" << setw(9) << v[i][j] << "\t" << setw(9) << h[i][j]+z[i][j] << "\t"<< setw(9)  << z[i][j] << "\t" << setw(9) << sqrt(pow(u[i][j],2)+pow(v[i][j],2)) << "\t" << setw(9) << sqrt(pow(u[i][j],2)+pow(v[i][j],2))/sqrt(GRAV*h[i][j]) << "\t" << setw(9) << h[i][j]*u[i][j] << "\t" << setw(9) << h[i][j]*v[i][j] << "\t" << setw(9) << h[i][j]*sqrt(pow(u[i][j],2)+pow(v[i][j],2)) << endl;
      }
      
    }// end of j loop
    outsave << endl;
  }// end of i loop
  outsave << endl;
  outsave << endl;
  outsave.close();
  
}


Gnuplot::~Gnuplot(){
}


